### PR TITLE
Add hacs support

### LINKED ISSUE #22: Make it available in HACS
Hi

How about make the integration available in HACS?

See docs here: https://hacs.xyz/docs/publish/start

### PR DESCRIPTION
**Pull request by olekenneth**
I opened the issue #22 to make this available in HACS. So instead of just nagging I wanted to give you a flying start. 

There is still some things missing, but I added the GitHub Action validator, so you can see for your self what's left to do.

Merging this will close #22

### CODE REVIEW

**Comment by echoromeo** [comment]
Cool! Thanks :)
Now, how do I use the GitHub Action validator?

**Comment by olekenneth** [comment]
It will be added to the repo automatically after merge. I think you can see the last run at my repo here: https://github.com/olekenneth/hanobo/runs/1911318000?check_suite_focus=true

**Comment by echoromeo** [comment]
..and the boring part of being a super awesome contributor, can you update the documentation with the change in path and a link to how to add it using HACS?

**Comment by olekenneth** [comment]
Yeah, sure. I'll update the docs

**Comment by olekenneth** [comment]
Done 🎉

**Comment by echoromeo** [comment]
Thanks!
Soo, how do we add the brand here? https://github.com/home-assistant/brands
Do we ask Glen Dimplex to do it?

**Pull request merged**
