### PR TITLE
Lock minor version for pynobo

### PR DESCRIPTION
**Pull request by oyvindwe**
This should fix issue #31

### CODE REVIEW

**Comment by echoromeo** [comment]
Would it not be more correct to fix this in pynobo? Either by fixing the compatibility issue or by bumping pynobo to 2.0.0?

**Comment by oyvindwe** [comment]
Thanks @echoromeo - good questions!

I don't think bumping pynobo to 2.0.0 helps, as the current requirement is `["pynobo>=1.1.2"]`. That said, since it obviously is not backwards compatible after all, it should be bumped anyways.

I am not sure if it is possible to fix the backwards compatibility issue with HA, as we need to create a separate event loop inside pynobo, but I can have a look at it later this week.

Btw, in HomeAssistant version must always be pinned: `"pynobo==1.1.2"`. Maybe a good practice in HACS integrations as well?

**Comment by echoromeo** [comment]
Yes, I should have used ^1.1.2 or ~1.1.2.

I do not mind using ==1.1.2 for this one

**Comment by oyvindwe** [comment]
> I do not mind using ==1.1.2 for this one

Done.

**Comment by echoromeo** [comment]
Thanks

**Pull request merged**
